---
- name: register newrelic key
  apt_key: url=http://download.newrelic.com/548C16BF.gpg state=present

- name: add newrelic default repositories
  apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present

- name: install newrelic php packages
  apt: pkg={{ item }} state=latest force=yes update_cache=yes
  with_items:
    - newrelic-php5

- name: set newrelic license
  lineinfile: "dest=/etc/php/mods-available/newrelic.ini state=present regexp='^newrelic.license' line='newrelic.license = "{{ newrelic.license }}"'"

- name: set newrelic app name
  lineinfile: "dest=/etc/php/mods-available/newrelic.ini state=present regexp='^newrelic.appname' line='newrelic.appname = "{{ newrelic.appname }}"'"

- name: activate newrelic
  shell: phpenmod newrelic
  notify: restart newrelic-daemon
